version: '3.4'

services:
  eventmanagement.webapi:
    image: ${DOCKER_REGISTRY-}eventmanagementwebapi
    build:
      context: .
      dockerfile: src/EventManagement.WebApi/Dockerfile

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    
  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    depends_on:
      - elasticsearch

networks:
  elastic:
    driver: bridge
    
volumes:
  elasticsearch-data:
    driver: local
 