version: '3.4'

services:
  eventmanagement.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_HTTPS_PORTS=443
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  elasticsearch:
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - bootstrap.memory_lock=true
      - cluster.routing.allocation.disk.threshold_enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g" 
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ${APPDATA}/Elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - elastic
  kibana:
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_URL=http://localhost:9200
    ports:
      - "5601:5601"
    networks:
      - elastic